webtalk_init -webtalk_dir /media/ritvik/Storage_SamsungSSD_500GB/projects/HDL/publish/fifo_sram/scripts/rundir/xsim.dir/defaultlib.fifo_sram_tb/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jul 20 00:11:39 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c56d758b-84f7-4812-b1d0-f4ad3ec89f89" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a30d9d55-e4a9-4ca6-a6e4-08376a326b5f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen Threadripper 2950X 16-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2019.111 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "167 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "117260_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1235224623 -regid "" -xml /media/ritvik/Storage_SamsungSSD_500GB/projects/HDL/publish/fifo_sram/scripts/rundir/xsim.dir/defaultlib.fifo_sram_tb/webtalk/usage_statistics_ext_xsim.xml -html /media/ritvik/Storage_SamsungSSD_500GB/projects/HDL/publish/fifo_sram/scripts/rundir/xsim.dir/defaultlib.fifo_sram_tb/webtalk/usage_statistics_ext_xsim.html -wdm /media/ritvik/Storage_SamsungSSD_500GB/projects/HDL/publish/fifo_sram/scripts/rundir/xsim.dir/defaultlib.fifo_sram_tb/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
